version: "3.7"
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    restart: on-failure
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
  ngproxy:
    image: nginx
    restart: on-failure
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "nginx:/etc/nginx"
volumes:
    jenkins-data:
        external: true
    nginx:
        external: true