version: "3.7"
networks:
  ol:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
services:
  percona:
    image: percona:5.6
    networks:
      ol:
        ipv4_address: 172.28.0.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 3306
        published: 3308
    environment:
        MYSQL_ROOT_PASSWORD: numessage
    volumes:
      - "./numsg.sql:/numsg.sql"
      - "./percona-run.sh:/percona-run.sh"
    command: sh /percona-run.sh
  zookeeper:
    image: zookeeper
    networks:
      ol:
        ipv4_address: 172.28.0.4
    depends_on:
      - percona
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 2181
        published: 2181
  numsglocal:
    image: ecr.vip.ebayc3.com/numessage/numsg:local-latest
    networks:
      ol:
        ipv4_address: 172.28.0.3
    depends_on:
      - percona
      - zookeeper
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 8090
        published: 8090
    environment:
        JACOCO_ENABLE: "true"
        NUMSG_SERVER_LOCALIZED: "true"
    command: ["numsg-server-0.0.4-SNAPSHOT/bin/start-all.sh"]