version: "3.2"
services:
  percona:
    image: percona:5.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # should use long syntax
    ports:
      - target: 3306
        published: 3308
        protocol: tcp
        mode: host
    networks:
      - webnet
    environment:
        MYSQL_ROOT_PASSWORD: numessage
networks:
  webnet: